{% set name = "nushell" %}
{% set version = "0.92.1" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: bd4d0b90ff7ba53ac888df755372a794a907f93963e26ff8f441347aa0ff5a95

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cargo-bundle-licenses
  host:
    - zlib
    - openssl

test:
  commands:
    - nu --version
    - nu --help

about:
  home: https://nushell.sh
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY_LICENSES.yaml
  summary: A new type of shell
  dev_url: https://github.com/nushell/nushell

extra:
  recipe-maintainers:
    - pavelzw
